# Default system properties included when running spark-submit.
# This is useful for setting default environmental settings.

# Hadoop FS
spark.hadoop.fs.defaultFS hdfs://namenode:9000

# Spark configuration
spark.master spark://spark-master:7077
spark.executor.memory 1g
spark.executor.cores 2
spark.driver.memory 1g
spark.driver.cores 1

# Use YARN shuffle service for better data locality
spark.shuffle.service.enabled true

# Eventlog for history server (optional)
# spark.eventLog.enabled true
# spark.eventLog.dir hdfs://namenode:9000/spark-logs
# spark.history.fs.logDirectory hdfs://namenode:9000/spark-logs

# Application configuration
spark.app.name Spark-Application
spark.local.dir /var/lib/spark/work

# Serialization
spark.serializer org.apache.spark.serializer.KryoSerializer
