services:
  # Trending Words Transformation Job
  trending-words-job:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trending-words-job
    environment:
      HDFS_INPUT: "hdfs://namenode:9000/raw_zone"
      HDFS_OUTPUT: "hdfs://namenode:9000/work_zone/table_trending_words"
      SPARK_MASTER: "spark://spark-master:7077"
      EXECUTOR_MEMORY: "2G"
      EXECUTOR_CORES: "2"
    volumes:
      - ./data/input:/data/input
      - ./data/output:/data/output
      - ./:/app
    networks:
      - hadoop_network

networks:
  hadoop_network:
    driver: bridge
